# Generated by Django 4.2.3 on 2023-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='media/1658384701097-01.jpeg', upload_to='images/'),
        ),
    ]
