# Generated by Django 4.2.3 on 2023-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/1658384701097-01.jpeg', null=True, upload_to='images/'),
        ),
    ]
