# Generated by Django 4.2.3 on 2023-07-11 10:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/1658384701097-01.jpeg', null=True, upload_to=api.models.upload_to),
        ),
    ]
